---
title: "About"
---
## Lynda M. Kellam

### Penn Libraries
As the [Snyder-Granader Director of Research Data & Digital Scholarship at the University of Pennsylvania Libraries](https://www.library.upenn.edu/rdds), I manage a team of librarians who support data management, GIS, repository services, digital humanities and publishing, AI/ML, and statistical software. In addition to managing the department, I support qualitative researchers with data analysis. 

### Data Rescue
As a founding organizer of the [Data Rescue Project](https://www.datarescueproject.org), I research and write about the Federal Statisitcal System and government information preservation. 

### History
As a historian, I've focused on the nineteenth century American and British anti-imperial movements. My dissertation [Looking Forward: Sovereign Responsibilities in the United States and Great Britain, 1894-1920](https://libres.uncg.edu/ir/uncg/listing.aspx?id=46651) is available from [UNCG's NC DOCKS](https://libres.uncg.edu/ir/uncg/). Feel free to read and send me feedback! My current project examines Lucia Ames Mead who is best known as a peace advocate but had ties to the anti-imperialist movement. 

## Experience

* University of Pennsylvania Libraries
  + Snyder-Granader Director of Research Data & Digital Scholarship | February 2024 - present
  + Interim Director of Research Data & Digital Scholarship | July 2023 - January 2024
  + Head of Research Data Services | January 2022 - February 2023

* Cornell University
  + Senior Data Librarian/Associate Librarian | July 2019 - December 2021

* Unversity of North Carolina at Greensboro
  + Research Data Coordinator & Associate Professor | May 2007 - July 2019
  + Assistant Director of International & Global Studies | March 2016 - December 2019
  
## Education

* Ph.D. in American History 
  + University of North Carolina at Greensboro | May 2023
* Master in Library & Information Sciences
  + University of North Carolina at Greensboro | May 2007
* MA in Political Science 
  + University of Wisconsin, Madison | May 2000
* BA in Political Science & International & Global Studies
  + University of North Carolina at Greensboro | December 1997
