---
title: "Recent Talks and Interviews"
---


## Talks
* Invited keynote: “Championing Public Data: Data Professionals in Civic Life” for the International Association for Social Science Information Service and Technology Conference. Virtual. June 2, 2026.

* Inivited panel: “Future Directions for Digital Scholarship" for the Forging the Future of Digital Scholarship: People, Projects, Priorities 
symposium at Brown University. Providence, RI. May 1, 2026.

* Invited keynote: “Public Data Stewardship in Challenging Times" for the Research Libraries UK Conference. Virtual. March 26, 2026.

* Invited keynote: “Our Data, Our Right: Community, Data, and Democracy" with Mikala Narlock for the International Digital Curation Conference 2026. Zagreb, Croatia. February 18, 2026.

* Invited panel: [The Day Federal Data Went Dark: A Year of Monitoring and Action](https://youtu.be/nUwReBMnwqQ?si=JYqBnSKKR93PSGuY). Webinar with Data Index and friends. January 29, 2026. 

* Invited keynote: Saving What Counts: Lessons from Data Rescues for Today's Data Librarians. Southeast Data Librarian Symposium 2025, [https://doi.org/10.5281/zenodo.17329549](https://doi.org/10.5281/zenodo.17329549). October 8, 2025. 

* Invited keynote: Rescuing and Preserving Public Data. Penn State Open Scholarship Bootcamp 2025, State College, PA, [https://doi.org/10.5281/zenodo.16884194](https://doi.org/10.5281/zenodo.16884194). August 15, 2025.

* Invited keynote: "KEEP CALM AND FLOAT ON: Data Rescue and You" for the Association for Computers and the Humanities Conference (ACH2025), [https://doi.org/10.5281/zenodo.15649310](https://doi.org/10.5281/zenodo.15649310). June 12, 2025.

## Interviews
* Casy Calver. ["Podcast: Behind the Masthead" special series: a conversation with Lynda Kellam, PhD."](https://rss.com/podcasts/behindtheevidence/2517826/). Behind the Evidence. February 3, 2026.
* Sam Cole. ["Podcast: A Massive Archiving Effort at National Parks."](https://www.404media.co/podcast-a-massive-archiving-effort-at-national-parks-with-jenny-mcburney-and-lynda-kellam/)." 404 Media. November 10, 2025.
* TaRhonda Thomas. ["Fears for Independence Mall as Trump orders removal of displays that 'disparage' American history."](https://6abc.com/post/fears-independence-mall-trump-orders-removal-displays-disparage-american-history/17829883/) 6 Action News Philadelphia. September 16, 2025.
* Hans Buetow. [Rescuing Public Datasets the U.S. Gov't Deletes.](https://www.neverpo.st/rescuing-public-datasets-the-u-s-govt-deletes/) NeverPost Podcast. July 30, 2025.
* [The Knowledge Commons Podcast: Lynda Kellam](https://www.youtube.com/watch?v=LQVYGZMK3Rw). July 25, 2025.
* [THE podcast: university libraries – and librarians – that are leading the change.](https://www.timeshighereducation.com/campus/campus-talks-university-libraries-and-librarians-are-leading-change) Times Higher Education. July 10, 2025. 
* Lauren Collister. [With Government Data at Risk, These Volunteers are Taking Action.](https://katinamagazine.org/content/article/future-of-work/2025/with-government-data-at-risk-volunteers-take-action) Katina Magazine. May 6, 2025. 
* Lisa Peet. [Coordinating Data Rescue Efforts.](https://www.libraryjournal.com/story/coordinating-data-rescue-efforts-qa-with-lynda-kellam) Library Journal. April 2, 2025.